---
# tasks file for redis
- name: install redis
  package:
    name: "{{ redis_packages }}"
    state: present
  register: redis_install_redis
  until: redis_install_redis is succeeded
  retries: 3

- name: configure redis
  template:
    src: "redis.conf-{{ ansible_distribution }}.j2"
    dest: "{{ redis_configuration_directory }}/{{ redis_configuration_file }}"
    owner: "{{ redis_owner }}"
    group: "{{ redis_group }}"
    mode: "{{ redis_mode }}"
  notify:
    - restart redis

- name: start and enable redis
  service:
    name: "{{ redis_service }}"
    state: started
    enabled: yes
  when:
    - ansible_virtualization_type != "docker"
