Vagrant.configure("2") do |config|
    # OS for each VM
    config.vm.box = "centos/7"

    config.vm.define "ansible" do |control|
        control.vm.hostname = "ansible.aceit.com"
        control.vm.network "private_network", ip: "192.168.2.100"
        control.vm.synced_folder "../ansible", "/ansible" 
        control.vm.provider :virtualbox do |vb|
            vb.memory = 2048
            vb.cpus = 2
        end
        control.vm.provision "shell" do |sh|
            sh.inline = "sudo yum update -y"
            sh.inline = "sudo yum install -y epel-repease"
            sh.inline = "sudo yum install -y wget python3 ansible tree curl"
        end
    end 

    config.vm.define "master" do |master|
        master.vm.hostname = "master.aceit.com"
        master.vm.network "private_network", ip: "192.168.2.101"
        master.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", 2048]
            vb.customize ["modifyvm", :id, "--cpus", 2]
        end
    end

    config.vm.define "node1" do |node1|
        node1.vm.hostname = "node1.aceit.com"
        node1.vm.network "private_network", ip: "192.168.2.102"
        node1.vm.provider :virtualbox do |vb|
           vb.memory =  1024
           vb.cpus = 1
        end
    end

    config.vm.define "node2" do |node2|
        node2.vm.hostname = "node2.aceit.com"
        node2.vm.network "private_network", ip: "192.168.2.103"
        node2.vm.provider :virtualbox do |vb|
           vb.memory = 1024
           vb.cpus = 1
        end
    end

end 
