Vagrant.configure("2") do |config|
    # OS for each VM
    config.vm.box = "centos/7"

    # base cpu and memory for each  VM
    # any per vm customization must be done in each config section
    config.vm.provider :virtualbox do |vbox|
        vbox.cpus = 2
        vbox.memory = 4096
    end 
    
    # defining the ansiblecontrol machine
    config.vm.define "ansible" do |control|
        control.vm.hostname = "ansible.aceit.com"
        control.vm.synced_folder  "../../ansible", "/ansible", nfs: true
        control.vm.network "public_network", ip: "192.168.0.10"
        # bootstrapping  required packages for ansible
        control.vm.provision :shell do |sh|
            sh.inline = "sudo yum install -y epel-release"
            sh.inline = "sudo yum update -y"
            sh.inline = "sudo yum install -y python3 ansible python3-pip docker docker-py"
        end
    end 
end 