---
# vars file for artifactory
_artifactory_requirements:
  default: []
  Archlinux:
    - bash
  Debian:
    - procps
  Fedora:
    - procps
  Ubuntu:
    - procps

artifactory_requirements: "{{ _artifactory_requirements[ansible_distribution] | default(_artifactory_requirements['default']) }}"

artifactory_zip: "https://dl.bintray.com/jfrog/artifactory/jfrog-artifactory-oss-{{ artifactory_version }}.zip"
artifactory_home: "{{ artifactory_download_directory }}/artifactory-oss-{{ artifactory_version }}"
artifactory_user: artifactory
artifactory_group: artifactory

# Set the parameters required for the service.
service_list:
  - name: artifactory
    description: Start script for Artifactory
    start_command: "{{ artifactory_home }}/bin/artifactory.sh start"
    stop_command: "{{ artifactory_home }}/bin/artifactory.sh stop"
    type: forking
    status_pattern: artifactory
