---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint:
  name: yamllint
driver:
  name: docker
platforms:
  - name: jenkins-debian-stable
    image: debian:stable
    pre_build_image: yes
provisioner:
  name: ansible
  playbooks:
    prepare: ../resources/prepare-java11.yml
    converge: ../resources/playbook.yml
scenario:
  name: debian-stable
