---
# handlers file for docker_ce
- name: restart docker_ce
  service:
    name: "{{ docker_ce_service }}"
    state: restarted
  when:
    - ansible_virtualization_type != "docker"

- name: apt update cache
  apt:
    update_cache: yes
  register: docker_ce_apt_update_cache
  until: docker_ce_apt_update_cache is succeeded
  retries: 3
