---
galaxy_info:
  author: Robert de Bock
  role_name: firewall
  description: Manage firewall ports on all (known) Linux operating systems.
  license: Apache-2.0
  company: none
  min_ansible_version: 2.6

  platforms:
    - name: ArchLinux
      version:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      version:
        - 6
        - 7
    - name: Fedora
      versions:
        - all
    - name: OpenSUSE
      versions:
        - all
    - name: Ubuntu
      versions:
        - artful
        - bionic

  galaxy_tags:
    - alpine
    - centos
    - debian
    - el
    - fedora
    - firewall
    - firewalld
    - opensuse
    - rhel
    - server
    - system
    - ubuntu

dependencies: []
