---
# vars file for python_pip
_python_pip_packages:
  Alpine:
    - py-pip
    - python3-dev
  Archlinux:
    - python-pip
    - python-setuptools
  Debian:
    - python3-pip
    - python3-setuptools
  CentOS-7:
    - python-pip
    - python-setuptools
  RedHat:
    - python3-pip
    - python3-setuptools
  Suse:
    - python-pip
    - python-setuptools

python_pip_packages: "{{ _python_pip_packages[ansible_distribution ~ '-' ~ ansible_distribution_major_version] | default(_python_pip_packages[ansible_os_family] | default(_python_pip_packages['default'])) }}"
